# Generated by Django 3.2.5 on 2021-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
