# Generated by Django 3.2.5 on 2021-10-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0002_botuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=1000)),
                ('canceld', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=True)),
            ],
        ),
    ]
