# Generated by Django 3.2.5 on 2021-10-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='canceld',
            new_name='canceled',
        ),
    ]
