# Generated by Django 3.2.5 on 2021-10-23 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0004_rename_canceld_product_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tgdelo.botuser'),
        ),
    ]
