# Generated by Django 3.2.5 on 2021-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0005_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='canceled',
            new_name='closed',
        ),
        migrations.AddField(
            model_name='product',
            name='declined',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='opened',
            field=models.BooleanField(default=True),
        ),
    ]
