# Generated by Django 3.2.5 on 2021-10-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgdelo', '0006_auto_20211028_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='approved',
        ),
        migrations.AddField(
            model_name='product',
            name='approved1',
            field=models.BooleanField(default=None),
        ),
    ]
