# Generated by Django 3.2.5 on 2022-02-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Tuser_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', models.CharField(default='Other', max_length=10)),
                ('lat', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('is_bot', models.BooleanField(default=False)),
                ('language_code', models.CharField(default='am', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=22)),
                ('buser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=0)),
                ('message_id', models.IntegerField()),
                ('text', models.CharField(max_length=4096)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bbbot.user')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like', models.ManyToManyField(to='bbbot.BotUser')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='bbbot.botuser')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='bbbot.botuser')),
            ],
        ),
    ]
