# Generated by Django 3.2.5 on 2022-02-12 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likess',
            fields=[
                ('like_id', models.IntegerField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like', models.ManyToManyField(to='bbbot.BotUser')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='bbbot.botuser')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='bbbot.botuser')),
            ],
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
