# Generated by Django 3.2.5 on 2021-09-24 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='deep_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked_bot',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_moderator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
    ]
