# Generated by Django 3.2.5 on 2022-02-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0002_auto_20220212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='likess',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
