# Generated by Django 3.2.5 on 2022-02-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0003_likess_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
