# Generated by Django 3.2.5 on 2021-09-29 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0003_auto_20210929_0247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='auther',
        ),
    ]
