# Generated by Django 3.2.5 on 2022-02-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0004_botuser_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='liked_by',
            field=models.IntegerField(default=0),
        ),
    ]
