# Generated by Django 3.2.5 on 2021-09-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0004_rename_author_post_auther'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auther',
        ),
    ]
