# Generated by Django 3.2.5 on 2021-10-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0006_auto_20211001_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
