# Generated by Django 3.2.5 on 2021-10-01 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0007_message_chat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
    ]
