# Generated by Django 3.2.5 on 2021-10-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0012_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone_Vs_Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
