# Generated by Django 3.2.5 on 2021-10-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0013_phone_vs_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
