# Generated by Django 3.2.5 on 2021-10-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0015_auto_20211007_0110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
