# Generated by Django 3.2.5 on 2021-10-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0016_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='body',
            new_name='text',
        ),
        migrations.AddField(
            model_name='data',
            name='comments',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
