# Generated by Django 3.2.5 on 2021-10-10 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0017_auto_20211007_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=22)),
                ('buser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bbbot.user')),
            ],
        ),
    ]
