# Generated by Django 3.2.5 on 2021-10-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbbot', '0020_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='like',
            field=models.ManyToManyField(to='bbbot.BotUser'),
        ),
    ]
